# Generated by Django 5.2.17 on 2026-09-12 17:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="头像",
            ),
        ),
    ]
