# Generated by Django 5.2.17 on 2026-09-12 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="分类名"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, verbose_name="URL 标识"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=100, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="标签名"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, verbose_name="URL 标识"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="资源名称")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="留空自动生成；中文标题自动生成会为空，此时 URL 使用数字 ID",
                        max_length=140,
                        verbose_name="URL 标识",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="列表页展示的一句话介绍，留空则自动截取简介前 60 字",
                        max_length=200,
                        verbose_name="卡片摘要",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="支持换行；建议写软件简介、本版特点",
                        verbose_name="详细介绍",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="当前版本"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/%Y/%m/",
                        verbose_name="封面图",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="首页置顶"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="resources.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resources",
                        to="resources.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源",
                "verbose_name_plural": "资源",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="例如：本地下载 / 百度网盘 / 蓝奏云",
                        max_length=50,
                        verbose_name="按钮名称",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("local", "本地文件（服务器磁盘）"),
                            ("external", "外部链接（网盘）"),
                        ],
                        default="external",
                        max_length=20,
                        verbose_name="链接类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="link_type=本地文件 时必填",
                        null=True,
                        upload_to="files/%Y/%m/",
                        verbose_name="本地文件",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="link_type=外部链接 时必填，包含 https:// 前缀",
                        verbose_name="外链地址",
                    ),
                ),
                (
                    "extract_code",
                    models.CharField(
                        blank=True,
                        help_text="网盘提取码，可留空",
                        max_length=30,
                        verbose_name="提取码",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小（字节）"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=10, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "is_broken",
                    models.BooleanField(
                        default=False,
                        help_text="由「检查外链状态」任务自动标记",
                        verbose_name="外链疑似失效",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后检测时间"
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="resources.resource",
                        verbose_name="所属资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "下载链接",
                "verbose_name_plural": "下载链接",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=60, verbose_name="版本号")),
                (
                    "content",
                    models.TextField(
                        help_text="一条一行，或用换行分隔多条", verbose_name="更新内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="记录时间"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="resources.resource",
                        verbose_name="所属资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "更新日志",
                "verbose_name_plural": "更新日志",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="resources.resource",
                        verbose_name="资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "resource"), name="uniq_favorite_user_resource"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, verbose_name="评论内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="显示")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论者",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="resources.resource",
                        verbose_name="所属资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "-created_at"],
                        name="resources_c_resourc_0d6047_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["-updated_at"], name="resources_r_updated_99b32a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_published", "-is_pinned", "-updated_at"],
                name="resources_r_is_publ_e578b1_idx",
            ),
        ),
    ]
