# Generated by Django 5.2.17 on 2026-09-12 17:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadlink",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="link_type=本地文件 时必填",
                null=True,
                upload_to="files/%Y/%m/",
                validators=[core.validators.validate_upload_size],
                verbose_name="本地文件",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="封面图",
            ),
        ),
    ]
